# Generated by Django 5.2.16 on 2026-07-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_timings',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='education',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='verification_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('doctor', 'Doctor'), ('admin', 'Admin'), ('support', 'Support')], default='client', max_length=20),
        ),
    ]
