# Generated by Django 5.2.16 on 2026-07-12 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('doctors', 'Doctors')], default='doctors', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('source', models.CharField(choices=[('openstreetmap', 'OpenStreetMap'), ('self_registered', 'Self-Registered')], default='openstreetmap', max_length=20)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], default='unverified', max_length=20)),
                ('raw_osm_tags', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
